---
title: "Descriptive statistics for ART utilisation over time"
subtitle: "Complete case data"
author: "Oisin Fitzgerald"
output:
  html_document:
    toc: true
---

```{r,echo=FALSE}
knitr::opts_chunk$set(echo=FALSE,message=FALSE,warning=FALSE)
```

# Introduction

Descriptive analysis of ART utilisation from 

```{r}
### packages, functions
library(data.table)
library(ggplot2)
library(magrittr)

### import data
art_dat <- readRDS("../data/art_covar_2002_2014.rds")
setDT(art_dat)

```

# Data

Several countries are removed from the analysis due to poor data quality (or missing data in the case of Taiwan)

```{r}
# country exclusions
countries_remove <- c("SaudiArabia", "UnitedArabEmirates", "Jordan", "Lebanon", "Bahrain",
                       "SyrianArabRepublic", "Morocco",
                       "Tunisia", "Libya", "Palestine,Stateof", "Egypt",
                       "Taiwan")
art_dat[,exclude := fifelse(country %in% countries_remove,TRUE,FALSE,FALSE)]
art_dat[,country := factor(country)]

# middle east, north africa variable
me_na <- c("SaudiArabia", "UnitedArabEmirates", "Jordan", "Lebanon", "Bahrain",
                       "SyrianArabRepublic", "Morocco",
                       "Tunisia", "Libya", "Palestine,Stateof", "Egypt")
art_dat[,me_na := fifelse(country %in% me_na,1,0,0)]
```


# High level description

```{r}
# years
art_dat[exclude==FALSE & !is.na(art_utilisation),.N,by=year] %>%
  ggplot(aes(x = year,y = N)) +
  geom_line() +
  geom_label(aes(label=N)) +
  scale_x_continuous(breaks=2002:2014) +
  labs(title="ART utilisation: # countries")
```

```{r}
# years
art_dat[exclude==FALSE & !is.na(gii_un),.N,by=year] %>%
  ggplot(aes(x = year,y = N)) +
  geom_line() +
  geom_label(aes(label=N)) +
  scale_x_continuous(breaks=2002:2014) +
  labs(title="GII: # countries")
```